# Generated by Django 5.1.7 on 2025-03-19 18:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название дерева"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        upload_to="tree_types/", verbose_name="Изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид дерева",
                "verbose_name_plural": "Виды деревьев",
            },
        ),
        migrations.CreateModel(
            name="PlantingSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_type",
                    models.CharField(
                        choices=[
                            ("yard", "Мой двор"),
                            ("public", "Территория, требующая улучшения"),
                        ],
                        max_length=10,
                        verbose_name="Тип участка",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="planting_sites/", verbose_name="Фотография"
                    ),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Локация")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planting_sites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Участок для посадки",
                "verbose_name_plural": "Участки для посадки",
            },
        ),
        migrations.CreateModel(
            name="TreeServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название услуги"),
                ),
                ("description", models.TextField(verbose_name="Описание услуги")),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Контактный телефон"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик услуг",
                "verbose_name_plural": "Поставщики услуг",
            },
        ),
        migrations.CreateModel(
            name="TreePlantingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество деревьев",
                    ),
                ),
                (
                    "price_per_tree",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за дерево"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В ожидании"),
                            ("approved", "Одобрено"),
                            ("completed", "Завершено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Примечания"),
                ),
                (
                    "planting_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.plantingsite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planting_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tree_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.treetype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на посадку",
                "verbose_name_plural": "Запросы на посадку",
                "ordering": ["-created_at"],
            },
        ),
    ]
